### ISSUE TITLE
Some things I noticed:

### ISSUE THREAD

**Issue by Yulife** [RootsTeam/Goetia#1]
1: I would scale down the altar model in GUI because it overgoes the 16x16
2: Creative tab needs to be localized
3: There should be a few commands, e.g. for adding Impurity or unlocking knowledge
4: Is the altar GUI buggy? It just shows Impurity text :smile: 
5: The Soul Focus works without holding the button but when you select a focus point and drag it across the screen you have to hold the button for it not to cancel the GUI
6: I know you are not a fan of animated items but having a flaring soul focus while rightclicking the soul focus would really add spice

**Comment by elucent** [comment]
1: It'll be remodeled anyway, I just didn't take the time to do so during TMT.

2: It's localized in the official jarfile, I just haven't pushed it yet.

3: In the realm of "didn't spend time on it for TMT, will make in the future".

4: The altar gui will show all the spells you currently have unlocked. You need higher impurity to see anything.

5: Yeah, you're supposed to click and drag the whole symbol in one go.

6: Maybe. Probably wouldn't be hard to make that happen, but again, not worth the time in the 96 hours. I was actually thinking of making it draw back like a bow, since items that draw back like that will keep drawing back while you're in a GUI unless you tell them to stop, and it will be released as soon as you close the GUI.
