### ISSUE TITLE
The Alignment Icon needs some default position tweaking

### ISSUE THREAD

**Issue by squirrelkiller** [RootsTeam/Goetia#8]
So I create a pack known as Safety Lost, and well Goetia has been there for quite a while now, and these recent updates brought something to my attention, the Icon for alignment is having some issues with the default positioning.

One person has reported it blocking vision of their first hot bar slot, I have seen it beside the hot bar with my own window, while others have had this issue:

https://cdn.discordapp.com/attachments/230503218298224640/245084446829707264/2016-11-07_02.16.37.png

I can't really set a good starting config as a pack developer when everyone's experience is so wildly different, and as a pack developer the ownest is on me to make sure the packaged configs work for the majority of users, so I have decided I would suggest some fix on your end.

I can think of a few fixes:

Option 1 Find a place to put it that has it far out of the way by default.
Option 2 Have it hidden by default and only appear after actually using the mod and gaining (im)purity.
Option 3 Put a config command and a chat alert to use it to allow customization of the HUD, Similar to Ars Magica 2's command.

Ideally all three of these would be best, but individually they would be a half decent band aid solution for now.

**Comment by werty1124** [comment]
I'll get his fixed ASAP though it doesn't seem to happen to me quite a few people are mentioning it

**Comment by squirrelkiller** [comment]
Some further tests show it has to do with resolution and GUI size. So it is an unlikely thing to be seen normally in basic tests.

**Comment by DeGariless** [comment]
Can you make the icon not show up unless you start using the mod? Some people that play the modpack might not be interested in Goetia and might have no idea what that icon is for.

**Comment by APolarBaer** [comment]
i get this aswell

**Comment by AnZaNaMa** [comment]
Fixed - the icon should now always render in the lower-left corner of the screen and not interfere with the hotbar or anything (unless your screen is so small it can't even fit the hotbar). If you want to tweak the position of it, you can change the offset in the config.

In regards to hiding the indicator, I don't believe that would be a wise decision, as of right now, because there is a mechanic that awards you with impurity for killing animals and purity for killing monsters. So, either it would just appear the first time you kill anything, or your level of impurity would be changing without you knowing it. Then, you decide to start the mod after a while and decide you want to go angelic, but you somehow have 1000 impurity already because you're a sheep murderer.

There's a possibility this could change in the future, but for now we'll leave it as-is.
